/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:    sensirion-driver-generator 0.9.1
 * Product:      scd30
 * Version:      None
 */
/*
 * Copyright (c) 2022, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "scd30_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

static uint8_t _i2c_address;

void init_driver(uint8_t i2c_address) {
    _i2c_address = i2c_address;
}

int16_t scd30_await_data_ready() {
    uint16_t data_ready = 0;
    int16_t local_error = 0;
    local_error = scd30_get_data_ready(&data_ready);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    while (data_ready == 0) {
        sensirion_hal_sleep_us(100000);
        local_error = scd30_get_data_ready(&data_ready);
        if (local_error != NO_ERROR) {
            return local_error;
        }
    }
    return local_error;
}

int16_t scd30_blocking_read_measurement_data(float* co2_concentration,
                                             float* temperature,
                                             float* humidity) {
    int16_t local_error = 0;
    local_error = scd30_await_data_ready();
    if (local_error != NO_ERROR) {
        return local_error;
    }
    local_error =
        scd30_read_measurement_data(co2_concentration, temperature, humidity);
    return local_error;
}

int16_t scd30_start_periodic_measurement(uint16_t ambient_pressure) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x10);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        local_buffer, local_offset, ambient_pressure);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    return local_error;
}

int16_t scd30_stop_periodic_measurement() {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[2] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x104);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_set_measurement_interval(uint16_t interval) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x4600);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(local_buffer,
                                                        local_offset, interval);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_get_measurement_interval(uint16_t* interval) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x4600);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *interval = sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_get_data_ready(uint16_t* data_ready_flag) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x202);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *data_ready_flag = sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_read_measurement_data(float* co2_concentration,
                                    float* temperature, float* humidity) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[18] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x300);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 12);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *co2_concentration = sensirion_common_bytes_to_float(&local_buffer[0]);
    *temperature = sensirion_common_bytes_to_float(&local_buffer[4]);
    *humidity = sensirion_common_bytes_to_float(&local_buffer[8]);
    return local_error;
}

int16_t scd30_activate_auto_calibration(uint16_t do_activate) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5306);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        local_buffer, local_offset, do_activate);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_get_auto_calibration_status(uint16_t* is_active) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5306);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *is_active = sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_force_recalibration(uint16_t co2_ref_concentration) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5204);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        local_buffer, local_offset, co2_ref_concentration);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_get_force_recalibration_status(uint16_t* co2_ref_concentration) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5204);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *co2_ref_concentration =
        sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_set_temperature_offset(uint16_t temperature_offset) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5403);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(
        local_buffer, local_offset, temperature_offset);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_get_temperature_offset(uint16_t* temperature_offset) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5403);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *temperature_offset = sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_get_altitude_compensation(uint16_t* altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5102);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *altitude = sensirion_common_bytes_to_uint16_t(&local_buffer[0]);
    return local_error;
}

int16_t scd30_set_altitude_compensation(uint16_t altitude) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[5] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0x5102);
    local_offset = sensirion_i2c_add_uint16_t_to_buffer(local_buffer,
                                                        local_offset, altitude);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    return local_error;
}

int16_t scd30_read_firmware_version(uint8_t* major, uint8_t* minor) {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[3] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0xd100);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(10 * 1000);
    local_error =
        sensirion_i2c_read_data_inplace(_i2c_address, local_buffer, 2);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    *major = (uint8_t)local_buffer[0];
    *minor = (uint8_t)local_buffer[1];
    return local_error;
}

int16_t scd30_soft_reset() {
    int16_t local_error = NO_ERROR;
    uint8_t local_buffer[2] = {0};
    uint16_t local_offset = 0;
    local_offset =
        sensirion_i2c_add_command_to_buffer(local_buffer, local_offset, 0xd304);
    local_error =
        sensirion_i2c_write_data(_i2c_address, local_buffer, local_offset);
    if (local_error != NO_ERROR) {
        return local_error;
    }
    sensirion_i2c_hal_sleep_usec(2000 * 1000);
    return local_error;
}
